"""actions: task_action_rules + task_actions (Phase 5, spec 006) +
users.gmail_granted_scopes

Revision ID: 0011_actions
Revises: 0010_jobs

Two brand-new tables plus one nullable column on an existing table — no data
migration involved (mirrors 0010_jobs' rationale). task_actions' CHECK
constraint (exactly one of source_event_id/source_link_id) and its two
partial unique indexes are dialect-portable: the CHECK's boolean `!=` is
valid on both SQLite and Postgres, and `postgresql_where=`/`sqlite_where=`
each compile to that dialect's own partial-index syntax (mirrors
task_events.uq_task_event_msg_field from 0007_tasks, which used raw SQL
instead since it only needed one dialect-portable WHERE clause — these two
indexes get theirs from typed kwargs instead so each dialect's DDL is
generated by SQLAlchemy rather than hand-written twice).
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import JSONB

revision: str = "0011_actions"
down_revision: Union[str, Sequence[str], None] = "0010_jobs"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        "users",
        sa.Column(
            "gmail_granted_scopes",
            sa.JSON().with_variant(JSONB(), "postgresql"),
            nullable=True,
        ),
    )

    op.create_table(
        "task_action_rules",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column("task_id", sa.String(36), sa.ForeignKey("tasks.id"), nullable=False),
        sa.Column("trigger", sa.String(32), nullable=False),
        sa.Column("trigger_params", sa.JSON().with_variant(JSONB(), "postgresql"), nullable=True),
        sa.Column("action_type", sa.String(32), nullable=False),
        sa.Column("action_params", sa.JSON().with_variant(JSONB(), "postgresql"), nullable=True),
        sa.Column("mode", sa.String(16), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False, server_default="false"),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
    )
    op.create_index("ix_task_action_rules_task_id", "task_action_rules", ["task_id"])

    op.create_table(
        "task_actions",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column("task_id", sa.String(36), sa.ForeignKey("tasks.id"), nullable=False),
        sa.Column("rule_id", sa.String(36), sa.ForeignKey("task_action_rules.id"), nullable=False),
        sa.Column("source_event_id", sa.String(36), sa.ForeignKey("task_events.id"), nullable=True),
        sa.Column("source_link_id", sa.String(36), sa.ForeignKey("task_thread_links.id"), nullable=True),
        sa.Column("thread_id", sa.String(36), nullable=True),
        sa.Column("gmail_thread_id", sa.String(64), nullable=False),
        sa.Column("action_type", sa.String(32), nullable=False),
        sa.Column("action_params", sa.JSON().with_variant(JSONB(), "postgresql"), nullable=True),
        sa.Column("status", sa.String(16), nullable=False),
        sa.Column("result", sa.JSON().with_variant(JSONB(), "postgresql"), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("executed_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "(source_event_id IS NULL) != (source_link_id IS NULL)",
            name="ck_task_actions_one_source",
        ),
    )
    op.create_index("ix_task_actions_task_id", "task_actions", ["task_id"])
    op.create_index(
        "uq_task_actions_rule_event", "task_actions", ["rule_id", "source_event_id"],
        unique=True,
        postgresql_where=sa.text("source_event_id IS NOT NULL"),
        sqlite_where=sa.text("source_event_id IS NOT NULL"),
    )
    op.create_index(
        "uq_task_actions_rule_link", "task_actions", ["rule_id", "source_link_id"],
        unique=True,
        postgresql_where=sa.text("source_link_id IS NOT NULL"),
        sqlite_where=sa.text("source_link_id IS NOT NULL"),
    )


def downgrade() -> None:
    op.drop_index("uq_task_actions_rule_link", table_name="task_actions")
    op.drop_index("uq_task_actions_rule_event", table_name="task_actions")
    op.drop_index("ix_task_actions_task_id", table_name="task_actions")
    op.drop_table("task_actions")

    op.drop_index("ix_task_action_rules_task_id", table_name="task_action_rules")
    op.drop_table("task_action_rules")

    op.drop_column("users", "gmail_granted_scopes")
